sudo: required
language: python

services:
  - docker

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

before_script:
  - mv secrets_redacted.yaml secrets.yaml
  - docker pull homeassistant/home-assistant:latest
script:
  - ./verify.sh
