language: python
python:
  - "3.4"
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

before_install:
  - mv secrets_redacted.yaml secrets.yaml
  - mkdir -p /etc/letsencrypt/live/graph.cyberkov.at && mv .travis/*.pem /etc/letsencrypt/live/graph.cyberkov.at/
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
