#- platform: manual
#  name: Alarmanlage
#  code: !env_var HA_ALARM_CODE
#  pending_time: 60
#  trigger_time: 120
#- platform: mqtt
#  name: Alarmanlage
#  code: !env_var HA_ALARM_CODE

#  https://community.home-assistant.io/t/a-different-take-on-an-alarm-system/7809
- platform: bwalarm
  name: House
  pending_time: 60
  trigger_time: 300
  alarm: switch.alarm
  warning: switch.warning
  headsup:
    - binary_sensor.wohnzimmertuer_state
    - binary_sensor.windfangtuer_state
    - binary_sensor.schlafzimmer_links_sabotage
    - binary_sensor.schlafzimmer_rechts_sabotage
  immediate:
    - binary_sensor.barbarafenster_state
    - binary_sensor.dominikfenster_state
    - binary_sensor.hannesfenster_state
    - binary_sensor.hannestuer_state
    - binary_sensor.kuechefenster_state
    - binary_sensor.schlafzimmer_links_state
    - binary_sensor.schlafzimmer_rechts_state
    - binary_sensor.vorzimmerogfenster_state

    - binary_sensor.barbara_fenster_sabotage
    - binary_sensor.dominik_fenster_sabotage
    - binary_sensor.og_bewegungsmelder_sabotage
    - binary_sensor.og_fenster_sabotage
    - binary_sensor.esszimmer_bewegungsmelder_sabotage
    - binary_sensor.kueche_fenster_sabotage
    - binary_sensor.windfang_tuer_sabotage
    - binary_sensor.wohnzimmer_tuer_sabotage
    - binary_sensor.hannes_bewegungsmelder_sabotage
    - binary_sensor.hannes_fenster_sabotage
    - binary_sensor.hannes_tuer_sabotage
  delayed:
    - binary_sensor.wohnzimmertuer_state
    - binary_sensor.windfangtuer_state
    - binary_sensor.schlafzimmer_links_sabotage
    - binary_sensor.schlafzimmer_rechts_sabotage
  notathome:
    - binary_sensor.esszimmerbewegungsmelder_motion
    - binary_sensor.hannesbewegungsmelder_motion
    - binary_sensor.vorzimmerogbewegungsmelder_motion
