homeassistant: !include config/core/homeassistant.yaml
influxdb: !include config/core/influxdb.yaml

conversation:
discovery:
config:

frontend:
history: !include config/core/history.yaml
http: !include config/core/http.yaml
#logbook:
#  exclude:
#    domains:
#      - sun
#      - weblink
recorder: !include config/core/recorder.yaml
sun:
updater:
  include_used_components: true
zeroconf:
tts:
  - platform: google
    language: 'de'
    cache: true
    cache_dir: 'tts'
#  - platform: voicerss
#    api_key: !secret HA_VOICERSS
#    language: 'de-de'

homematic: !include config/core/homematic.yaml

#alexa: !include alexa.yaml
#input_select: !include input_select.yaml
#weblink: !include weblink.yaml
alarm_control_panel: !include config/alarm_control_panel.yaml
apiai: !include config/apiai.yaml
automation: !include_dir_merge_list config/automation
binary_sensor: !include_dir_merge_list config/devices/binary_sensors
device_tracker: !include config/devices/device_tracker.yaml
group: !include_dir_named config/groups
light: !include_dir_merge_list config/devices/lights
logger: !include config/core/logger.yaml
media_player: !include config/devices/media_player.yaml
notify: !include config/notify.yaml
panel_iframe: !include panel_iframe.yaml
proximity: !include config/proximity.yaml
script: !include_dir_named config/scripts
sensor: !include_dir_merge_list config/devices/sensors
shell_command: !include config/shell_command.yaml
switch: !include_dir_merge_list config/devices/switches
zone: !include_dir_merge_list config/zones

#scene: !include_dir_merge_list scenes
emulated_hue:
  advertise_ip: 192.168.1.4
  expose_by_default: true
rfxtrx: !include config/core/rfxtrx.yaml

mqtt: !include config/core/mqtt.yaml

#mqtt_eventstream:
#  publish_topic: homeassistant/events/master
#  subscribe_topic: homeassistant/events/slave

#mysensors:
#  gateways:
#    - device: mqtt
#      persistence_file: '/config/mysensors.json'
#      topic_in_prefix: 'mysensors/in'
#      topic_out_prefix: 'mysensors/out'
#  version: 2.0

#panel_custom:
#    - name: alarm
#      sidebar_title: Alarm
#      sidebar_icon: mdi:security-home
#      config:
#          alarmid: alarm_control_panel.house

google:
  client_id: !secret HA_GOOGLE_OAUTH_ID
  client_secret: !secret HA_GOOGLE_OAUTH_SECRET

zwave: !include config/core/zwave.yaml
