homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HA_HOME_LATITUDE
  longitude: !secret HA_HOME_LONGITUDE
  # Impacts weather/sunrise data
  elevation: 169
  # C for Celsius, F for Fahrenheit
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  customize: !include_dir_merge_named customizations

influxdb:
  host: 127.0.0.1
  database: homeassistant
  port: '8086'
  default_measurement: 'hass.state'

conversation:
discovery:
config:

frontend:
history:
  include:
    domains:
      - climate
      - switch
      - binary_sensor
http:
  cors_allowed_origins:
    - https://haus.cyberkov.at
    - https://haus.cyberkov.lan
  ssl_certificate: !secret HA_HTTP_CERT
  ssl_key: !secret HA_HTTP_KEY
  base_url: haus.cyberkov.at
  use_x_forwarded_for: true
  api_password: !secret HA_HTTP_LOGIN
  ip_ban_enabled: false
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 172.17.0.0/24
    - 192.168.1.0/25
#logbook:
#  exclude:
#    domains:
#      - sun
#      - weblink
recorder:
  purge_days: 3
  db_url: !secret HA_RECORDER_DB
sun:
updater:
zeroconf:
tts:
  - platform: google
    language: 'de'
    cache: true
    cache_dir: 'tts'
#  - platform: voicerss
#    api_key: !secret HA_VOICERSS
#    language: 'de-de'

homematic:
  hosts:
    rf:
      ip: '192.168.1.6'
      port: 2001
#      resolvenames: xml
      resolvenames: json
      username: !secret HA_HOMEMATIC_LOGIN
      password: !secret HA_HOMEMATIC_PASSWORD
      primary: true
      variables: true
  local_ip: '192.168.1.4'
  local_port: 8943

alarm_control_panel: !include alarm_control_panel.yaml
automation: !include_dir_merge_list automation
#input_select: !include input_select.yaml
script: !include_dir_named scripts
device_tracker: !include device_tracker.yaml
group: !include_dir_named groups
light: !include_dir_merge_list lights
logger: !include logger.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
binary_sensor: !include_dir_merge_list binary_sensors
panel_iframe: !include panel_iframe.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
#weblink: !include weblink.yaml
zone: !include_dir_merge_list zones
proximity: !include proximity.yaml
apiai: !include apiai.yaml
#alexa: !include alexa.yaml
shell_command: !include config/shell_command.yaml

#scene: !include_dir_merge_list scenes
emulated_hue:
  advertise_ip: 192.168.1.4
  expose_by_default: true
rfxtrx:
  device: '/dev/ttyUSB0'
  debug: false

mqtt:
  broker: 192.168.1.4
  port: 1883
  client_id: home-assistant
  protocol: 3.1
#  broker: m21.cloudmqtt.com
#  port: 27670
  username: !secret HA_MQTT_LOGIN
  password: !secret HA_MQTT_PASSWORD

#mqtt_eventstream:
#  publish_topic: homeassistant/events/master
#  subscribe_topic: homeassistant/events/slave

#mysensors:
#  gateways:
#    - device: mqtt
#      persistence_file: '/config/mysensors.json'
#      topic_in_prefix: 'mysensors/in'
#      topic_out_prefix: 'mysensors/out'
#  version: 2.0

#panel_custom:
#    - name: alarm
#      sidebar_title: Alarm
#      sidebar_icon: mdi:security-home
#      config:
#          alarmid: alarm_control_panel.house

google:
  client_id: !secret HA_GOOGLE_OAUTH_ID
  client_secret: !secret HA_GOOGLE_OAUTH_SECRET

zwave:
  usb_path: /dev/ttyACM0
#  config_path: /usr/local/share/python-openzwave/config
#  autoheal: false
# polling_interval: 2000
