- platform: kodi
  host: http://192.168.1.11
  port: 8080
  name: kodi_wohnzimmer
- platform: kodi
  host: http://192.168.1.10
  port: 8080
  name: kodi_hannes
- platform: sonos
  name: wohnzimmer
  hosts: 192.168.1.86
- platform: sonos
  name: bad
  hosts: 192.168.1.120
- platform: sonos
  name: sauna
  hosts: 192.168.1.19
- platform: sonos
  name: kche
  hosts: 192.168.1.130
