- name: Hannes Movie
  entities:
    light.hannes_1:
      state: on
      brightness: 30
    light.hannes_2:
      state: on
      brightness: 30
    switch.hannesdeckenlicht: off
- name: Hannes Normal
  entities:
    light.hannes_1:
      state: on
      brightness: 100
    light.hannes_2:
      state: on
      brightness: 100
    switch.hannesdeckenlicht: on
