- alias: 'Gelsenstecker off'
  trigger:
    - platform: state
      entity_id: binary_sensor.schlafzimmer_links_state
      to: 'off'
    - platform: state
      entity_id: binary_sensor.schlafzimmer_rechts_state
      to: 'off'
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
  condition:
    - condition: state
      entity_id: switch.it_stecker_2
      state: "on"
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.schlafzimmer_links_state
          state: 'off'
        - condition: state
          entity_id: binary_sensor.schlafzimmer_rechts_state
          state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: light.it_stecker_2
  
