who_cooks:
  name: Who cooks today
  options:
    - Hannes
    - Barbara
  initial: Hannes
  icon: mdi:panda
log_level:
  name: Log Level
  options:
    - critical
    - fatal
    - error
    - warning
    - warn
    - info
    - debug
    - notset
  initial: info
