- platform: darksky
  api_key: !env_var HA_FORECAST_API
  monitored_conditions:
    - summary
    - icon
    - precip_intensity
    - precip_probability
    - precip_type
    - hourly_summary
    - wind_speed
    - daily_summary
