- platform: mqtt
  state_topic: "hm/status/Gaszaehler/GAS_POWER"
  name: "gas_power"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.val }}'
- platform: mqtt
  state_topic: "hm/status/Gaszaehler/GAS_ENERGY_COUNTER"
  name: "gas_energy_counter"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.val }}'
- platform: mqtt
  state_topic: "hm/status/Stromzaehler/POWER"
  name: "strom_power"
  unit_of_measurement: "W"
  value_template: "{{ value_json.val }}"
- platform: mqtt
  state_topic: "owntracks/cyberkov/lgg3"
  name: "Battery LG G3"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

#- platform: template
#  sensors:
#    sauna_heizung_valve:
#      entity_id: climate.sauna_heizung
#      value_template: '{{ states.climate.sauna_heizung.attributes.Valve }}'
#      unit_of_measurement: '%'
