- platform: mqtt
  state_topic: "hm/status/Gaszaehler/GAS_POWER"
  name: "gas_power"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.val }}'
- platform: mqtt
  state_topic: "hm/status/Stromzaehler/POWER"
  name: "strom_power"
  unit_of_measurement: "W"
  value_template: "{{ value_json.val }}"
- platform: mqtt
  state_topic: "owntracks/cyberkov/lgg3"
  name: "Battery LG G3"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
