entities:
  - sensor.geschirrspuler_current
  - sensor.geschirrspuler_energy_counter
  - sensor.geschirrspuler_power
  - sensor.geschirrspuler_voltage
  - sensor.geschirrspuler_frequency
  - switch.geschirrspuler
  - binary_sensor.kuechefenster_state
  - climate.kuecheheizung
  - sensor.kuechetemperatur_humidity
  - sensor.kuechetemperatur_temperature
  - media_player.kuche
  - sensor.mold_kueche

