entities:
  - sensor.luftentfeuchter_current
  - sensor.luftentfeuchter_energy_counter
  - sensor.luftentfeuchter_power
  - sensor.luftentfeuchter_voltage
  - sensor.luftentfeuchter_frequency
  - switch.luftentfeuchter
  - sensor.stats_sauna_humidity_mean
  - climate.sauna_heizung
  - sensor.sauna_temperatur_humidity
  - sensor.sauna_temperatur_temperature
  - media_player.sauna
  - sensor.mold_sauna
  - switch.mqtt_sauna_luftentfeuchter
  - binary_sensor.luftentfeuchter_status
  - sensor.luftentfeuchter_on_today
  - automation.luftentfeuchter
