entities:
  - binary_sensor.schlafzimmer_links_state
  - binary_sensor.schlafzimmer_rechts_state
  - sensor.mold_schlafzimmer
  - sensor.schlafzimmertemperatur_humidity
  - sensor.schlafzimmertemperatur_temperature
  - climate.schlafzimmerheizunglinks
  - climate.schlafzimmerheizungrechts
  - switch.it_stecker_2
  - light.nachtkasterl
  - media_player.schlafzimmer
