entities:
  - sensor.waschmaschine_current
  - sensor.waschmaschine_energy_counter
  - sensor.waschmaschine_power
  - sensor.waschmaschine_voltage
  - sensor.waschmaschine_frequency
  - switch.waschmaschine
  - switch.wirtschaftsraumtherme
  - sensor.gas_power
  - sensor.gas_energy_counter
  - sensor.strom_power
  - sensor.gaszaehler_energy_counter
  - sensor.gaszaehler_gas_energy_counter
  - sensor.gaszaehler_gas_power
  - sensor.gaszaehler_power
  - sensor.stromzaehler_energy_counter
  - sensor.stromzaehler_gas_energy_counter
  - sensor.stromzaehler_gas_power
  - sensor.stromzaehler_power
  - switch.mqtt_wirtschaftsraum_therme
  - sensor.waschmaschine_status
