- platform: google_travel_time
  name: Google Travel Time
  api_key: !secret HA_GOOGLE_API_KEY
  origin: !secret HA_HOME_LATLON
  destination: !secret HA_HANNES_WORK_LATLON
  options:
    departure_time: now
    mode: transit
