alias: "Home Asssistant Update"
trigger:
  - platform: state
    entity_id: updater.updater
action:
    service: notify.hannes
    data:
      message: "New version {{ states.updater.updater.state }} of Home Assistant is available."
