alias: 'Luftentfeuchter'
trigger:
  - platform: numeric_state
    entity_id: sensor.sauna_temperatur_humidity
    above: 62
    below: 57
  - platform: numeric_state
    entity_id: sensor.mold_sauna
    above: 80
    below: 70
  - platform: template
    value_template: >
      {% if states.sensor.sauna_temperatur_humidity.state|float <= 57
      or states.sensor.sauna_temperatur_humidity.state|float >= 62
      or states.sensor.mold_sauna.state|float <= 70
      or states.sensor.mold_sauna.state|float >= 80
       %}true{% endif %}
  - platform: time
    minutes: '/15'
    seconds: 0
action:
  - service_template: >
      {% set high_hum = 62 -%}
      {% set low_hum = 57  -%}
      {% set high_mold = 80 -%}
      {% set low_mold = 70 -%}
      {% if states.sensor.sauna_temperatur_humidity.state|float <= low_hum -%}
      switch.turn_off
      {% elif states.sensor.sauna_temperatur_humidity.state|float >= high_hum -%}
      switch.turn_on
      {% endif -%}
    entity_id: switch.luftentfeuchter
