alias: 'Luftentfeuchter'
trigger:
  - platform: numeric_state
    entity_id: sensor.sauna_temperatur_humidity
    above: 62
    below: 57
  - platform: numeric_state
    entity_id: sensor.mold_sauna
    above: 80
    below: 70
action:
  - service_template: >
      {% set high_hum = 62 %}
      {% set low_hum = 57  %}
      {% set high_mold = 80 %}
      {% set low_mold = 70 %}

      {% if (states.sensor.sauna_temperatur_humidity.state|float <= low_hum
         or states.sensor.mold_sauna.state|float <= low_mold )
      %}
        switch.turn_off
      {% elif (states.sensor.sauna_temperatur_humidity.state|float >= high_hum
         or states.sensor.mold_sauna.state|float >= high_mold )
      %}
        switch.turn_on
      {% endif %}
    entity_id: switch.luftentfeuchter
  - service: notify.slack
    data_template:
      message: >
        Sauna Luftfeuchte betraegt {{states.sensor.sauna_temperatur_humidity.state}}%, Schimmel {{states.sensor.mold_sauna.state}}%. trigger: {{ trigger.from_state.state }} to {{ trigger.to_state.state }}
