# If current between 30 and 45, washing mashine is in standby
alias: Waschmaschine fertig notify
trigger:
- platform: numeric_state
  entity_id: sensor.waschmaschine_current
  below: 45
condition:
  - condition: numeric_state
    entity_id: sensor.waschmaschine_current
    above: 30
  - condition: state
    entity_id: device_tracker.cyberkov_lgg3
    state: 'home'
  - condition: state
    entity_id: switch.sleeping
    state: 'off'
action:
  service: notify.hannes
  data_template:
    message: Waschmaschine ist fertig.
